spring.application.name=student-backend

# Primary DB (Render) - Spring Boot tự động nhận
spring.datasource.url=jdbc:postgresql://dpg-d6o28s7afjfc73aqo55g-a.singapore-postgres.render.com:5432/dtdm_udfr?sslmode=require&TimeZone=UTC
spring.datasource.username=dtdm_udfr_user
spring.datasource.password=f0kvrjLPJPjQL6WvUmZPWa4Ap6C90pQ3
spring.datasource.driver-class-name=org.postgresql.Driver

# Secondary DB (Railway)
secondary.datasource.url=jdbc:postgresql://hopper.proxy.rlwy.net:33654/railway?sslmode=require&options=-c%20TimeZone=Asia/Ho_Chi_Minh
secondary.datasource.username=postgres
secondary.datasource.password=fQHLohPGIuccVtcWdLLIUsRcDvJsRJNl
secondary.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jackson.time-zone=Asia/Ho_Chi_Minh
server.port=${PORT:8080}