spring.application.name=student-backend

# PostgreSQL Render
spring.datasource.url=jdbc:postgresql://dpg-d6o28s7afjfc73aqo55g-a.singapore-postgres.render.com/dtdm_udfr?sslmode=require
spring.datasource.username=dtdm_udfr_user
spring.datasource.password=f0kvrjLPJPjQL6WvUmZPWa4Ap6C90pQ3
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA - tự động tạo bảng students
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Port
server.port=${PORT:8080}